- name: Play for task level variables
  hosts: all
  tasks:
    - name: Print URL1
      ansible.builtin.debug:
        msg: URL -{{URL}}
      vars: 
        URL: task.example.com
    
    - name: print URL2
      ansible.builtin.debug:
        msg: URL - {{URL}}
      vars: 
        URL: scond.task.com
